### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by Dradden** [Kerwood/rtorrent.auto.install#10]
Would be awesome if you could add SSL for Apache for added security :)

**Comment by dvu0704** [comment]
Yeah, that will be super awesome for me too :). Is it something you can add-on the next release please? Very please? :)

**Comment by Kerwood** [comment]
Jesus.. Just set it up already ! :D

**Comment by jdupl** [comment]
If I wasn't so busy, I would do it.
