### ISSUE TITLE
wrong dir in Jessie script

### ISSUE THREAD

**Issue by terrorbobo** [Kerwood/rtorrent.auto.install#103]
Rtorrent-Auto-Install-3.0.2-Debian-Jessie
Line 796: mv -fv "$TEMP_PLUGIN_DIR"/* /var/www/rutorrent/plugins
should be: mv -fv "$TEMP_PLUGIN_DIR"/* /var/www/html/rutorrent/plugins

**Comment by Kerwood** [comment]
Fixed: https://github.com/Kerwood/rtorrent.auto.install/commit/82a3a357cb8c3d524f772441ead87a8248a3b343

Thanks a bunch..
