### ISSUE TITLE
Issue while installing RuTorrent

### ISSUE THREAD

**Issue by linkpad** [Kerwood/rtorrent.auto.install#104]
There's a problem with "wget http://dl.bintray.com/novik65/generic/rutorrent-3.6.tar.gz"

**Comment by jdupl** [comment]
please provide more information

**Comment by linkpad** [comment]
Sorry, issue at line 782 in Rtorrent-Auto-Install-3.0.2-Debian-Jessie, the wget get "20 redirections exceeded" error.

Also there's an error in Plugins-installer-script-3.0, the path "/var/www/rutorrent/plugins" is "/var/www/html/rutorrent/plugins" for Debian Jessie

**Comment by miracle091** [comment]
@linkpad try this version of the script https://gist.github.com/miracle091/61aa929646bd5a3afed9, for install rutorrent

Note: i updated it frequently so do a double check at the changes before use it

**Comment by linkpad** [comment]
@miracle091 Thanks for that version of the script, but I already installed rutorrent with a workaround. Anyway, I see that the Plugins installer script got updated, but there's some words spelt wrong.
https://github.com/Kerwood/rtorrent.auto.install/blob/master/Plugins-installer-script-3.1#L48 :
```echo " Is possible to create it, if you want."``` ->  ```echo "It's possible to create the folder."```

https://github.com/Kerwood/rtorrent.auto.install/blob/master/Plugins-installer-script-3.1#L49 :
 ```read -p " You want to create $DIR?" -n 1``` -> ```read -p " Do you want to create $DIR folder ?" -n 1```

https://github.com/Kerwood/rtorrent.auto.install/blob/master/Plugins-installer-script-3.1#L59 :
```error="${RED} Can't understand your choise!${NORMAL}"``` -> ```error="${RED} Can't understand your choice !${NORMAL}"```

**Comment by Kerwood** [comment]
@linkpad - Hey.. Do you know how to fork a project on Github ?.. 
The cool thing about Github is that you can fork this project, make changes to it, and make a pull request to the source aka. me. (You send a request for me to pull your changes)

**Comment by linkpad** [comment]
@Kerwood Yes, I know how to fork, but I though it wasn't necessary to fork for these little changes. Anyway, I'll do it asap ;)
