### ISSUE TITLE
Syntax Error for Plugin Install Only Script

### ISSUE THREAD

**Issue by dulguldur** [Kerwood/rtorrent.auto.install#109]
Hi!

First of all, tak, @Kerwood, for your script!

When trying to run the 'Plugins-installer-script-3.1.1' with "sudo ./Plugins-installer-script-3.1.1" I get this error in Ubuntu 14.04.2:

```
./Plugins-installer-script-3.1.1: line 61: syntax error near unexpected token `done' 
./Plugins-installer-script-3.1.1: line 61: `			done'   
```

I tried to resolve the problem myself, but I have 0% programming background (Ja, Jeg er en N00bspiller!) 

Something wrong with the syntax of the Bash if-statements? I dunno.

Thank you for your time.

**Comment by Kerwood** [comment]
How did you download the script ?

**Comment by dulguldur** [comment]
```
wget https://raw.githubusercontent.com/Kerwood/rtorrent.auto.install/master/Plugins-installer-script-3.1.1
```

**Comment by miracle091** [comment]
@Kerwood this can be closed
