### ISSUE TITLE
Default folder in 'Plugins-installer-script-3.1.1' + hangs

### ISSUE THREAD

**Issue by jotosmurf** [Kerwood/rtorrent.auto.install#112]
The default plugin folder path is */var/www/rutorrent/plugins*. This path does not exist in Debian 8.1 Jessie however.

I entered the correct path */var/www/**html**/rutorrent/plugins* but the script hangs. I believe there is something wrong.

**Comment by miracle091** [comment]
@Kerwood This can be closed.

**Comment by jotosmurf** [comment]
@miracle091 could you link to the commit change for this issue? Thanks!

**Comment by miracle091** [comment]
@jotosmurf #117 the solution is to make the default plugins folder a choise of the user when execute the script, as fallback the script select /var/www/rutorrent/plugins
