### ISSUE TITLE
Use the rtorrent IPv6 branch

### ISSUE THREAD

**Issue by RogerChern** [Kerwood/rtorrent.auto.install#115]
IPv6 is important for better connectivity, and there is a workable IPv6 branch of rtorrent. So could you please add an option in this setup script to install the IPv6 enabled version of rtorrent? Many thx and my regards.

**Comment by jdupl** [comment]
The branch has been unmaintained for 10 months now. The best solution would be to ask rakshasa to merge the ipv6 branch in master.

Meanwhile, replace [these lines](https://github.com/Kerwood/rtorrent.auto.install/blob/master/Rtorrent-Auto-Install-3.0.2-Debian-Jessie#L744-L746) with 
```
git clone https://github.com/rakshasa/rtorrent.git
cd rtorrent
git checkout ipv6
```
and continue the script normally.
