### ISSUE TITLE
directory error on raspbian 3.0.2

### ISSUE THREAD

**Issue by bicklp** [Kerwood/rtorrent.auto.install#116]
Hey
On line 674 of 3.0.2 raspbian wheezy script there is a command
cd xmlrpc-c
should this not be
cd xmlrpc  without the -c on the end

Its throwing an error when i try to run the script unless i change that directory name 
Cheers

**Comment by bicklp** [comment]
In fact the script doesn't seem to working at all....here is the result

--2015-09-26 14:15:45--  http://dl.bintray.com/novik65/generic/rutorrent-3.6.tar.gz
Resolving dl.bintray.com (dl.bintray.com)... 108.168.194.91, 108.168.194.92
Connecting to dl.bintray.com (dl.bintray.com)|108.168.194.91|:80... connected.
HTTP request sent, awaiting response... 302 
Location: http://d29vzk4ow07wi7.cloudfront.net/5870cddef717c83560e89aee56f2b7635ed1c90d?response-content-disposition=attachment%3Bfilename%3D%22rutorrent-3.6.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvNTg3MGNkZGVmNzE3YzgzNTYwZTg5YWVlNTZmMmI3NjM1ZWQxYzkwZD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMnJ1dG9ycmVudC0zLjYudGFyLmd6JTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDQzMjc3NjY1fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=mRN7fqvLpMnSZlig6DFAgFZKYJV118JWG6DOGB2zKAguxlpgSTrfM8Eh3VIvsThL0rVUe8vfTo5OaFniVUcSqXD6VNLtjbqsaL1GbbOC2Vcgo7~9TfxGwc2GBuDniFLvAhdZonKt7IF~v~iIVrY4VLYjigXLFXjM8Q7iPkvaS0p7BtdukltY71AcqWDfPiPMg6jEv5WtueOQeKtzSJe02e4RiZLD1FK~x-EEylWH0SprYVeJiwDiN6SkwsSDHBBL~emZ7SORJdt9cqiSZnTW9ZOqyUyMUOgCKEW9eZu0sOumqs4DIkULu1YYAMa2SrTL4g~vXFa22z7HM6xtPw0aow__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA [following]
--2015-09-26 14:15:46--  http://d29vzk4ow07wi7.cloudfront.net/5870cddef717c83560e89aee56f2b7635ed1c90d?response-content-disposition=attachment%3Bfilename%3D%22rutorrent-3.6.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvNTg3MGNkZGVmNzE3YzgzNTYwZTg5YWVlNTZmMmI3NjM1ZWQxYzkwZD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMnJ1dG9ycmVudC0zLjYudGFyLmd6JTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDQzMjc3NjY1fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=mRN7fqvLpMnSZlig6DFAgFZKYJV118JWG6DOGB2zKAguxlpgSTrfM8Eh3VIvsThL0rVUe8vfTo5OaFniVUcSqXD6VNLtjbqsaL1GbbOC2Vcgo7~9TfxGwc2GBuDniFLvAhdZonKt7IF~v~iIVrY4VLYjigXLFXjM8Q7iPkvaS0p7BtdukltY71AcqWDfPiPMg6jEv5WtueOQeKtzSJe02e4RiZLD1FK~x-EEylWH0SprYVeJiwDiN6SkwsSDHBBL~emZ7SORJdt9cqiSZnTW9ZOqyUyMUOgCKEW9eZu0sOumqs4DIkULu1YYAMa2SrTL4g~vXFa22z7HM6xtPw0aow__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA
Resolving d29vzk4ow07wi7.cloudfront.net (d29vzk4ow07wi7.cloudfront.net)... 54.192.36.69, 54.230.37.136, 54.192.37.13, ...
Connecting to d29vzk4ow07wi7.cloudfront.net (d29vzk4ow07wi7.cloudfront.net)|54.192.36.69|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 254520 (249K) [application/unknown]
Saving to: `rutorrent-3.6.tar.gz'

100%[=====================================================================================================>] 254,520      464K/s   in 0.5s    

2015-09-26 14:15:47 (464 KB/s) - `rutorrent-3.6.tar.gz' saved [254520/254520]

rutorrent/
rutorrent/favicon.ico
rutorrent/index.html
rutorrent/js/
rutorrent/js/jquery.flot.js
rutorrent/js/graph.js
rutorrent/js/plugins.js
rutorrent/js/rtorrent.js
rutorrent/js/jquery.js
rutorrent/js/webui.js
rutorrent/js/content.js
rutorrent/js/stable.js
rutorrent/js/objects.js
rutorrent/js/common.js
rutorrent/js/excanvas.js
rutorrent/css/
rutorrent/css/style.css
rutorrent/css/stable.css
rutorrent/php/
rutorrent/php/lock.php
rutorrent/php/doneplugins.php
rutorrent/php/lfs.php
rutorrent/php/getplugins.php
rutorrent/php/rtorrent.php
rutorrent/php/Snoopy.class.inc
rutorrent/php/util.php
rutorrent/php/setsettings.php
rutorrent/php/addtorrent.php
rutorrent/php/initplugins.php
rutorrent/php/xmlrpc.php
rutorrent/php/cache.php
rutorrent/php/test.sh
rutorrent/php/getsettings.php
rutorrent/php/settings.php
rutorrent/php/Torrent.php
rutorrent/images/
rutorrent/images/about.gif
rutorrent/images/status_down.gif
rutorrent/images/go.gif
rutorrent/images/props.gif
rutorrent/images/s.gif
rutorrent/images/quest.gif
rutorrent/images/i_bg.gif
rutorrent/images/header.gif
rutorrent/images/h.gif
rutorrent/images/status_up.gif
rutorrent/images/tstatus.png
rutorrent/images/close.png
rutorrent/images/bul.gif
rutorrent/images/toolbar.png
rutorrent/images/file.gif
rutorrent/images/dir.gif
rutorrent/images/btn_donate.gif
rutorrent/images/pnl_open.gif
rutorrent/images/r_bg.gif
rutorrent/images/menusel.gif
rutorrent/images/asc.gif
rutorrent/images/share.gif
rutorrent/images/settings.gif
rutorrent/images/bul_l.gif
rutorrent/images/t_bg.png
rutorrent/images/error.gif
rutorrent/images/ajax-loader.gif
rutorrent/images/world.gif
rutorrent/images/blank.gif
rutorrent/images/bul_f.gif
rutorrent/images/menuexp.gif
rutorrent/images/logo.png
rutorrent/images/label.gif
rutorrent/images/desc.gif
rutorrent/images/header_move.gif
rutorrent/images/pnl_close.gif
rutorrent/images/plugin.png
rutorrent/images/tb_bg.gif
rutorrent/conf/
rutorrent/conf/config.php
rutorrent/conf/.htaccess
rutorrent/conf/access.ini
rutorrent/conf/plugins.ini
rutorrent/conf/users/
rutorrent/share/
rutorrent/share/.htaccess
rutorrent/share/users/
rutorrent/share/torrents/
rutorrent/share/settings/
rutorrent/lang/
rutorrent/lang/en.js
rutorrent/lang/el.js
rutorrent/lang/fi.js
rutorrent/lang/sv.js
rutorrent/lang/de.js
rutorrent/lang/ru.js
rutorrent/lang/tr.js
rutorrent/lang/sr.js
rutorrent/lang/da.js
rutorrent/lang/pt.js
rutorrent/lang/lv.js
rutorrent/lang/uk.js
rutorrent/lang/zh-cn.js
rutorrent/lang/vi.js
rutorrent/lang/sk.js
rutorrent/lang/hu.js
rutorrent/lang/it.js
rutorrent/lang/pl.js
rutorrent/lang/zh-tw.js
rutorrent/lang/nl.js
rutorrent/lang/es.js
rutorrent/lang/fr.js
rutorrent/lang/cs.js
rutorrent/lang/langs.js
rutorrent/plugins/
removed `rutorrent-3.6.tar.gz'
ln: failed to create symbolic link `/etc/apache2/mods-enabled/scgi.load': No such file or directory
grep: /etc/apache2/ports.conf: No such file or directory
./Rtorrent-Auto-Install-3.0.2-Raspbian-Wheezy: line 760: /etc/apache2/ports.conf: No such file or directory
grep: /etc/apache2/apache2.conf: No such file or directory
./Rtorrent-Auto-Install-3.0.2-Raspbian-Wheezy: line 765: /etc/apache2/apache2.conf: No such file or directory
./Rtorrent-Auto-Install-3.0.2-Raspbian-Wheezy: line 770: /etc/apache2/sites-available/rutorrent.conf: No such file or directory
./Rtorrent-Auto-Install-3.0.2-Raspbian-Wheezy: line 787: a2ensite: command not found
apache2: unrecognized service
--2015-09-26 14:15:47--  https://raw.github.com/Kerwood/rtorrent.auto.install/master/Files/rtorrent-init
Resolving raw.github.com (raw.github.com)... 23.235.46.133
Connecting to raw.github.com (raw.github.com)|23.235.46.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/Kerwood/rtorrent.auto.install/master/Files/rtorrent-init [following]
--2015-09-26 14:15:50--  https://raw.githubusercontent.com/Kerwood/rtorrent.auto.install/master/Files/rtorrent-init
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.46.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.46.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4468 (4.4K) [text/plain]
Saving to: `/etc/init.d/rtorrent-init'

100%[=====================================================================================================>] 4,468       --.-K/s   in 0s      

2015-09-26 14:15:54 (15.9 MB/s) - `/etc/init.d/rtorrent-init' saved [4468/4468]

update-rc.d: using dependency based boot sequencing
cannot find rtorrent binary in PATH /usr/bin:/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin

**Comment by bicklp** [comment]
In the script raspbian script its trying to run 
APACHE-UTILS

but the function is called
APACHE_UTILS

and underscore not a dash

**Comment by Kerwood** [comment]
Fixed in below commit.. Thanks a bunch
https://github.com/Kerwood/rtorrent.auto.install/commit/0c8bb7c986f7329d1201cf55346ba3f387ac1c77
