### ISSUE TITLE
Will it be ok with existing webserver?

### ISSUE THREAD

**Issue by psycholyzern** [Kerwood/rtorrent.auto.install#121]
I have a server with virtualmin installed. Meaning that it has users, apache webserver, etc configured.
Will your script mess up with any configurations?

**Comment by miracle091** [comment]
Yes, just check the configuration of rutorrent cause override the default page of apache.

**Comment by Kerwood** [comment]
Most likely yes..

**Comment by psycholyzern** [comment]
Thanks :)
