### ISSUE TITLE
No connection to rTorrent/rTorrent can't start on Jessie

### ISSUE THREAD

**Issue by bhead9318** [Kerwood/rtorrent.auto.install#127]
After default installation with no plugins on Jessie with the Jessie script and loading ruTorrent in chrome, when I type sudo systemctl start rtorrent.service it returns nothing.  When I type just "rtorrent" the following is shown:

(18:09:31) Using 'epoll' based polling.
(18:09:31) Using 'epoll' based polling.
(18:09:31) Using 'epoll' based polling.
(18:09:31) Could not read resource file: ~/.rtorrent.rc

**Comment by Kerwood** [comment]
Some thing went wrong with our installation or you have changes something.
Check to see if ~/.rtorrent.rc actually is there and that the permissions are right.
