### ISSUE TITLE
Error defining APT_DEPENDENCIES function.

### ISSUE THREAD

**Issue by djbill** [Kerwood/rtorrent.auto.install#128]
On file: Rtorrent-Auto-Install-3.0.2-Raspbian-Wheezy

The function for installing dependencies is defined as "APT-DEPENDENCIES" but is called with "APT_DEPENDENCIES"

**Comment by Kerwood** [comment]
Changed the function name.. Thanks
https://github.com/Kerwood/rtorrent.auto.install/commit/abe107103b8bf8239986d910a1a6779e89f961f3
