### ISSUE TITLE
"The requested URL /rutorrent was not found on this server." Debian Jessie

### ISSUE THREAD

**Issue by annaparker** [Kerwood/rtorrent.auto.install#129]
Installation/compiling works good without issues. However rutorrent files aren't copied/unpacked to /var/www/. I have tested on two virtual servers with two other providers. The result is the same.

Version: 3.0.2 Jessie

**Comment by miracle091** [comment]
Because the apache package on jessie use another default folder. The default folder for jessie is this: ```/var/www/html/```

**Comment by Kerwood** [comment]
@annaparker - You are properly using the wrong script.

**Comment by TeHashX** [comment]
I get the same on ubuntu 15.04, Odroid XU4, trying Rtorrent-Auto-Install-1.1.0-Raspbian-Wheezy-Nginx now

**Comment by annaparker** [comment]
@Kerwood I'm sure I'm using **Rtorrent-Auto-Install-3.0.2-Debian-Jessie**

**Comment by TeHashX** [comment]
I found the culprit, is wget in line 783 wget http://dl.bintray.com/novik65/generic/rutorrent-3.6.tar.gz
"20 redirections exceeded"
and will not download rutorrent-3.6.tar.gz

**Comment by Kerwood** [comment]
https://github.com/Kerwood/rtorrent.auto.install/commit/f0dce18434f48fa163ea9e6dc464e21d27428663
https://github.com/Kerwood/rtorrent.auto.install/commit/e89297246fe9e321ee916ea824a4ed1a480e7832
https://github.com/Kerwood/rtorrent.auto.install/commit/b937066c2a86d25315a67266cfbff497a85eb975

Fixed :)

**Comment by TeHashX** [comment]
Thanks, same error for plugins, line 154 should be
```
curl -L "$url" -o $file
```

**Comment by Kerwood** [comment]
Fixed..

**Comment by annaparker** [comment]
Confirming, works flawaless now. However new problem has appeared. The plugins won't download, they throw an error on every plugin's download.
