### ISSUE TITLE
rtorrent doesn't start automatically on Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by annaparker** [Kerwood/rtorrent.auto.install#130]
After reboot, rtorrent won't boot up automatically. I have to login via SSH and start it manually. Tested on several clean VPS. Used Wheezy 3.0.2.

**Comment by jdupl** [comment]
Please use ubuntu script for ubuntu and not debian.

**Comment by Kerwood** [comment]
Please use Debian for the debian scripts.
