### ISSUE TITLE
Wrong date for any new torrents after a reboot

### ISSUE THREAD

**Issue by psycholyzern** [Kerwood/rtorrent.auto.install#138]
I rebooted my server, then I start rtorrent.
Then all new torrent will get a false date. Sone of them shown added on 1970, and some on 2014.
I dont know it it is a problem with rtorrent itself, just trying my luck here.
Thanks.

**Comment by Kerwood** [comment]
Hey mate.. That has nothing to do with this script :) .. Sorry
