### ISSUE TITLE
New versions (apache, rtorrent, rutorrent)

### ISSUE THREAD

**Issue by DarkHollow** [Kerwood/rtorrent.auto.install#141]
New version of **apache2** make this autoinstall not to work, at least on **Ubuntu 15.10**, for example the new directory for webserver is `/var/www/html`.
And new versions of **rtorrent** and **rutorrent** are available.

**Comment by Kerwood** [comment]
There are no versions of this script for Ubuntu.. Use Debian.

**Comment by DarkHollow** [comment]
Thank you.
