### ISSUE TITLE
Debian Jessie can't install rtorrent

### ISSUE THREAD

**Issue by 460990832** [Kerwood/rtorrent.auto.install#144]
Because xmlrpc can't be installed 
/tmp/xmlrpc/common.mk:601: recipe for target 'install-headers' failed
make[1]: *** [install-headers] Error 1
make[1]: Leaving directory '/tmp/xmlrpc/include'
/tmp/xmlrpc/common.mk:377: recipe for target 'include/install' failed
make: *** [include/install] Error 2

**Comment by Kerwood** [comment]
Looking in to it now..

**Comment by Kerwood** [comment]
Version 4.0.0 should be working again.. Please report back if not.
