### ISSUE TITLE
ARM64 - cheap hosts

### ISSUE THREAD

**Issue by nfguide** [Kerwood/rtorrent.auto.install#185]
Great work on the installation script.

Found a couple of issues when running the script on some Scaleway ARM64 host(s), in that not everything would build correctly. Didn't spend a lot of time troubleshooting, just noting it here, and no issue running the script and building on the x86_64 hosts.

Cheers!

**Comment by Kerwood** [comment]
Thanks.. Have a look at the docker container i build. Its much easier to deploy.
https://github.com/Kerwood/Rtorrent-LXC
