### ISSUE TITLE
Web Interface User and Password Prompt

### ISSUE THREAD

**Issue by sirmbhe** [Kerwood/rtorrent.auto.install#30]
Hello,

How is to activate user name & password prompt to access the web interface.
Right now, if I go to my web interface, it goes straight to the dashboard without prompting username and password first.

Thank you,
Dhavid

Ps. It's a great script btw :+1:

**Comment by sirmbhe** [comment]
Hello,

Although the issue was resolved, when I try your script today. i got an error messege like this : 

    [06.03.2015 15:19:47] Bad response from server: (404 [error,list]) <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found</h1> <p>The requested URL /RPC2 was not found on this server.</p> <hr> <address>Apache/2.2.22 (Debian) Server at [IP] Port 80</address> </body></html>

Any idea to solve this issue?

Thanks

**Comment by Kerwood** [comment]
I had a look at your server, added "ServerName localhost" to /etc/apache2/apache2.conf and restarted apache. Apparently that fixed it.

**Comment by sirib** [comment]
Hello Kerwood,

Thanks for the great and simple to use script.
Installation went smooth, but  the rutorrent web interface not prompting for username and password. Any idea how to fix it?.

Mvh,
Sri

**Comment by Kerwood** [comment]
https://github.com/Kerwood/rtorrent.auto.install#login-box-does-not-appear-after-install

**Comment by sirib** [comment]
I have already tried this and still no success. It would be of great help, if you can have a look at my server and figure out something.

**Comment by Kerwood** [comment]
What OS are you using ?

**Comment by sirib** [comment]
Ubuntu 14.04 and i am using your Ubuntu script.

**Comment by Kerwood** [comment]
Send me login details.
I need at user with root priviliges

**Comment by Kerwood** [comment]
patrick@kerwood.dk

**Comment by sirib** [comment]
email sent

**Comment by Kerwood** [comment]
This ---> https://github.com/Kerwood/rtorrent.auto.install#login-box-does-not-appear-after-install
Was the problem. You did not delete the plugins.

**Comment by sirib** [comment]
i deleted those plugins before. but after deletion, i had log in problems.
can you tell the steps you did. I was breaking my head to fix this.

**Comment by Kerwood** [comment]
```
sudo rm -rv /var/www/html/rutorrent/plugins/{httprpc,rpc.backup}
```

I dont know why but you renamed the folde `rpc` to `rpc.backup`

**Comment by sirib** [comment]
thanks for fixing it. one more thing, i forgot the password for the web-interface and idea how to reset it.

**Comment by Kerwood** [comment]
The user list is located at `/var/www/html/rutorrent/.htpasswd`
Just delete the line with your username and save.

To add another user just run `sudo htpasswd /var/www/html/rutorrent/.htpasswd USERNAME`

**Comment by sirib** [comment]
thanks a lot. it is working now.

**Comment by Pruney** [comment]
@Kerwood Are you still around.

I did the command but I can still connect with no login, this also popped up.

![image](https://user-images.githubusercontent.com/16701692/33323458-6cd122c0-d444-11e7-9673-de90fe725a0d.png)

**Comment by Pruney** [comment]
I funnily enough fixed it myself after posting. Always seems to happen.

I went into my sites-available/site.conf

and changed where it said AllowOverride None to AuthConfig and it is now asking me!

**Comment by Kerwood** [comment]
Thanks for posting your fix.
I would recommend user my docker container instead. Its much easier.
https://github.com/Kerwood/Rtorrent-LXC
