### ISSUE TITLE
Error rtorrent.rc & scgi

### ISSUE THREAD

**Issue by GostlingX** [Kerwood/rtorrent.auto.install#31]
OS: Debian 6 (Squeeze) (64 bits)

Rutorrent internal error (console)
Could not read resource file: ~/.rtorrent.rc

Rutorrent Site
No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.

**Comment by Kerwood** [comment]
Have you checked that the .rtorrent.rc file is available and readable, for the rtorrent user ?

**Comment by GostlingX** [comment]
no...on which directory I find it?

**Comment by Greqs** [comment]
/home/YOURS_USER_NAME/rtorrent.rc

**Comment by Kerwood** [comment]
Cant help you

**Comment by GostlingX** [comment]
Thk for instant close the issue...but not work

**Comment by Kerwood** [comment]
No.. Thank you for giving me so specific details about your issue. It really makes everything easy.
Its an rtorrent issue, or its your server. Not my script.

**Comment by GostlingX** [comment]
That's all I've done since before starting the installation script.

adduser rutorrent

During installation I inserted this user (rutorrent)

Installed, reboot the server and insert screen -fa -d -m -S rtorrent rtorrent

Rtorrent internal error (console)
Could not read resource file: ~/.rtorrent.rc

Rutorrent Site
No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.

I realized that the installation is very simple, I watched the video, but if once the installation is not working, and obviously I ask you ..

**Comment by Kerwood** [comment]
Where do you insert the "screen" line ?
You shouldnt have to do that.

**Comment by dvu0704** [comment]
Hi Kerwood,

I just installed fresh Ubuntu server 14.4 and latest rtorrent. Everything configured fine without any issue. But when I reboot the server the first time after rtorrent installed, I got this error below just like everyone else got.

No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.

Other ppl are saying, this is a bind issue, to fix it, simply edit the /var/www/html/rutorrent/conf/config.php

From:

$httpIP = null;				// IP string. Or null for any.

To

$httpIP = IP;				// IP string. Or null for any.

I got it fixed with previous installation, but not with this Ubuntu 14.4 version.

Starting/Stopping/Restarting service work fine, but auto restart on boot-up does not start it auto.

I checked the .rtorrent.rc file to make sure the system user account has read and write to the file or not, it does.

-rw-r--r-- 1 don don 3421 Mar 21 20:50 .rtorrent.rc

What's my next step here? Please advise.

Thanks!

**Comment by Kerwood** [comment]
If i understand you right, rtorrent wont start after boot. You have to start it manually.

The init script was initially made for Debian. (The script that starts and stops rtorrent with service rtorrent-init). I suspect that is the problem. And I dont think its only you. My guess is that it would properly not work on any Ubuntu system.

Try and start it after boot with crontab.
If you dont use password when using sudo you can write this line in your own crontab.
```
@reboot sudo service rtorrent-init start
```
 
Else write it in root crontab, without sudo.

**Comment by dvu0704** [comment]
You have understand me correctly.

I do use sudo with password, does that mean I don't have other option beside changing my system account with no password in-order to use the crontab?

**Comment by Kerwood** [comment]
No.. You turn off password for sudo, not your system account.

You have to open crontab with `crontab -e`, then add the line, close and save.

If you do not have disabled password on sudo, login as root and add the line in root's crontab, without sudo.

**Comment by dvu0704** [comment]
OK, here is what I did.

Disabled sudo password with the steps below

Edit the sudoers file:

sudo visudo
Find this line:

%sudo ALL=(ALL) ALL
Change the line:

%sudo ALL=(ALL) NOPASSWD: ALL
Save and Exit

Edit crontab

sudo nano /etc/crontab -e

Added a command line at the end of the crontab as

@reboot sudo service rtorrent-init start

Saved and reboot.

rtorrent still did not startup auto

**Comment by dvu0704** [comment]
After rebooted, I ran the command line below.

ps -ef|grep rtorrent

looks like rtorrent started under don's account, but the rutorrent did not started

don       2042  1971  0 23:39 pts/1    00:00:00 grep --color=auto rtorrent

**Comment by dvu0704** [comment]
The follow command I ran is

screen rottrent

That seem to startup rutorrent webgui. What am I missing here?

I can de-attached the screen without issue.

**Comment by Kerwood** [comment]
First of all.. If you run `sudo nano /etc/crontab -e` you are doing it wrong. Go back and read my last post again. 

Rutorrent webui is always on. Rutorrent is not the problem. 
Your problem is that rtorrent does not start, so rutorrent cannot connect to rtorrent.

**Comment by dvu0704** [comment]
I re-read your last post, but not sure what you mean. Are you telling me not to edit the crontab -e with sudo?

I tried that, but unable to save the file, permission denied.

Can I do this?

sudo su -

and then

nano /etc/crontab -e

and then add the line below?

@reboot sudo service rtorrent-init start

**Comment by Kerwood** [comment]
Dude.. You really need some basic Linux knowledge :)

Yes that should work.. If not Im out of ideas.

**Comment by dvu0704** [comment]
LOL, I told you, I am new to XUNIL :).

I just tried that, no go. with or without sudo in the crontab, the result is the same. For, I will start it up manually until you figure it out. If you can't, who does?
