### ISSUE TITLE
Site rutorrent does not exist!

### ISSUE THREAD

**Issue by WayneSheppard** [Kerwood/rtorrent.auto.install#34]
Right after finishing installing the plugins, I get this: "ERROR: Site rutorrent does not exist!".  The install finishes normally.  I can get to the Apache2 Debian Default Page at http:/xxx.xxx.xxx.xxx.  But when I go to http:/xxx.xxx.xxx.xxx/rutorrent, I get a 404 Not Found page.  The rutorrent files exist in /var/www/rutorrent:

    /var/www/rutorrent$ ls
    conf  css  favicon.ico  images  index.html  js  lang  php  plugins  share

This is on a clean install of Debian 8 stable (Jessie) technical preview (ALPHA) (64bits)

**Comment by Kerwood** [comment]
Jessie is not stable. The current active stable release is 7. The script does not support Debian 8.

**Comment by WayneSheppard** [comment]
yeah, I just tried it with Wheezy and it works.

**Comment by jdupl** [comment]
I will look into jessie support in the next week.
