### ISSUE TITLE
Support Debian Jessie

### ISSUE THREAD

**Issue by jdupl** [Kerwood/rtorrent.auto.install#35]
Jessie can't install rutorrent properly.
Bug detected from #34

**Comment by jdupl** [comment]
Problems is rutorrent tarball can't be fetched from Debian Jessie.

On Jessie, wget [loops on redirections](https://gist.github.com/jdupl/9083f596fdcdd0dfc8e3).

On Wheezy, wget converts url and fetch file [without problems](https://gist.github.com/jdupl/cdfe47af8db355ea2e24).

On Jessie, wget is `GNU Wget 1.16 built on linux-gnu.` with extensions `+digest +https +ipv6 +iri +large-file +nls +ntlm +opie +psl +ssl/gnutls` and on Wheezy 1.13 with extensions `+digest +https +ipv6 +iri +large-file +nls -ntlm +opie +ssl/gnutls`.

**Comment by jdupl** [comment]
A quick and dirty fix would be to use curl as the downloader.
It is to be noted that this bug also introduces a nasty [infinite loop](https://github.com/Kerwood/rtorrent.auto.install/blob/master/rtorrent.auto.install-NEWEST-VERSION#L728) as the file does not exist.

**Comment by Kerwood** [comment]
Thanks.. I'll look into the infinite loop.

**Comment by t4n017** [comment]
I tried the script in Jessie and it almost works.

It gives error in [line 725] (https://github.com/Kerwood/rtorrent.auto.install/blob/master/rtorrent.auto.install-NEWEST-VERSION#L725)
```*ERROR: Site rutorrent does not exist!*```

But it can be fixed just by adding **.conf** as extension to the **rutorrent** file.

Then ([line 705] (https://github.com/Kerwood/rtorrent.auto.install/blob/master/rtorrent.auto.install-NEWEST-VERSION#L705)):
```
Job for apache2.service failed. See 'systemctl status apache2.service' and 'journalctl -xn' for details.
Installation is complete..

Failed to start rtorrent-init.service: Unit rtorrent-init.service failed to load: No such file or directory.
```

```
t4n017@TANO-DEBIAN:/etc/apache2/mods-enabled$ sudo systemctl status apache2.service 
[...]
feb 23 00:54:48 TANO-DEBIAN apache2[17633]: Invalid ServerName "*" use ServerAlias to set multiple server names.
[...]
```

And also ([line 719] (https://github.com/Kerwood/rtorrent.auto.install/blob/master/rtorrent.auto.install-NEWEST-VERSION#L719)):
```
feb 23 00:28:59 TANO-DEBIAN apache2[17078]: Unknown Authz provider: Valid-User
```

I hope you can fix it soon.

**Comment by Kerwood** [comment]
Thanks for the report. I'll have a look at getting the script to run on Jessie.

**Comment by jotosmurf** [comment]
Hello, I ran into this too. Was wondering if you found the time to fix this issue?

**Comment by jdupl** [comment]
Jessie is now released; I thought the problem in wget would have been fixed by now.
I will take a look this afternoon. 

Replacing wget by curl will be a piece of cake, but I have to test the init script with systemd.

**Comment by Kerwood** [comment]
The init script will not work. And there might be other issues. I'll make a Jessie script when I have til time for it.

**Comment by jdupl** [comment]
@Kerwood this can be closed
