### ISSUE TITLE
Cannot GET /rutorrent

### ISSUE THREAD

**Issue by bitcasual** [Kerwood/rtorrent.auto.install#36]
Can't open the web front-end. Just get message "Cannot GET /rutorrent". This is on a clean install of latest stable debian 7 image for arm. Running on a beaglebone black. No strange error messages during install. I think it got something todo with apaches2 default configuration not working with the settings in this script

**Comment by Kerwood** [comment]
Sounds rather BeagleBone specific.. Sorry cant help you with that. But please post here if you find a solution.

**Comment by jdupl** [comment]
Does apache output any error ? Does the default page at / works ?

If you restart the service with `service apache2 restart` does it output any error ?

**Comment by jdupl** [comment]
@Kerwood can you reopen the issue ?

**Comment by bitcasual** [comment]
@jdupl No, nothing. "service apache2 restart" restarts ok. I've tried doing everything manually following [this guide](http://terminal28.com/how-to-install-and-configure-rutorrent-rtorrent-libtorrent-xmlrpc-screen-debian-7-wheezy/) as well, and get no issues or error messages at all during install. rtorrent works fine in command line.

**Comment by jdupl** [comment]
Can you post a gist of the apache configs in '/etc/apaches/sites-enabled' ?

Are you trying to connect to the webui from the same machine or another ? Perhaps the ip is wrong.

What exactly displays 'Just get message "Cannot GET /rutorrent".' Is it your browser or an apache error ?

**Comment by bitcasual** [comment]
@jdupl Different machine on same local network. Yes, it's just that single message with a white background. Using the internal ip and it's correct as I can reach http://<local ip>/Support/bone101/. 

https://gist.github.com/bitcasual/d4017e5edd8cf5952e74

I'm a beginner and this whole ordeal is a headache as well as learning experience.  I've never tinkered with stuff like this before but I think I'm starting to fit some pieces together.

**Comment by jdupl** [comment]
@ker

**Comment by jdupl** [comment]
@Kerwood issue can be reclosed it was beaglebone specific (apache not listening on port 80).
Perhaps the script could check if apache listens on port 80.
