### ISSUE TITLE
Dependency Problems

### ISSUE THREAD

**Issue by shauder** [Kerwood/rtorrent.auto.install#41]
root@debian:~#  apt-get install openssl git subversion apache2 apache2-utils build-essential libsigc++-2.0-dev libcurl4-openssl-dev automake libtool libcppunit-dev libncurses5-dev libapache2-mod-scgi php5 php5-curl php5-cli libapache2-mod-php5 screen unrar-free unzip
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    apache2 is already the newest version.
    apache2-utils is already the newest version.
    apache2-utils set to manually installed.
    openssl is already the newest version.
    libapache2-mod-scgi is already the newest version.
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created or been moved out of Incoming.   The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
     libcurl4-openssl-dev : Depends: libkrb5-dev but it is not going to be installed
                            Depends: librtmp-dev but it is not going to be installed
                            Depends: libssh2-1-dev but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.
    root@debian:~#

I tried this

    root@debian:~# sudo apt-get install -f
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

I am getting dependency problems trying to install this with Debian 7.8.

**Comment by jdupl** [comment]
Can you do a full update, upgrade and dist-upgrade ?

**Comment by shauder** [comment]
Hit http://ppa.launchpad.net trusty Release.gpg
    Get:1 http://security.debian.org squeeze/updates Release.gpg [836 B]
    Hit http://http.us.debian.org stable Release.gpg
    Get:2 http://security.debian.org squeeze/updates Release [86.9 kB]
    Hit http://ppa.launchpad.net trusty Release
    Hit http://http.us.debian.org stable Release
    Hit http://ppa.launchpad.net trusty/main Sources
    Hit http://http.us.debian.org stable/main amd64 Packages
    Hit http://ppa.launchpad.net trusty/main amd64 Packages
    Hit http://http.us.debian.org stable/contrib amd64 Packages
    Hit http://http.us.debian.org stable/non-free amd64 Packages
    Hit http://ppa.launchpad.net trusty/main Translation-en
    Hit http://http.us.debian.org stable/contrib Translation-en
    Get:3 http://security.debian.org squeeze/updates/main Sources [139 kB]
    Hit http://http.us.debian.org stable/main Translation-en
    Hit http://http.us.debian.org stable/non-free Translation-en
    Get:4 http://security.debian.org squeeze/updates/main amd64 Packages [367 kB]
    Ign http://security.debian.org squeeze/updates/main Translation-en_US
    Ign http://security.debian.org squeeze/updates/main Translation-en
    Fetched 594 kB in 4s (126 kB/s)
    Reading package lists... Done
    root@debian:~# apt-get upgrade
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    root@debian:~# apt-get dist-upgrade
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    Calculating upgrade... Done
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    root@debian:~#

**Comment by jdupl** [comment]
You have Squeeze (Debian 6) in your security sources. Wheezy is the Debian 7. 

You must update your apt sources in /etc/apt/sources.list and change `squeeze` to `wheezy` or `stable`. Then do a full update and dist-upgrade.

Also I find it strange that some hits go to http://ppa.launchpad.net trusty . Did you add ubuntu sources ? They might create some other problems.

**Comment by Greqs** [comment]
Try:

nano /etc/sources.list

and # all  http://ppa.launchpad.net trusty/main   repository 

Ctrl + o  
Ctrl + x

apt-get update 
apt-get upgrade

**Comment by jdupl** [comment]
No @Greqs it is the squeeze source list that causes the problems. 
These packages just got updated in Debian Wheezy (2 days ago).

**Comment by Greqs** [comment]
@jdupl Yes - you right

Just edit sources.list delete your repository and add wheezy one
For example:

nano /etc/apt/sources.list

## DEBIAN
deb http://ftp.debian.org/debian wheezy main contrib non-free
# deb-src http://ftp.debian.org/debian wheezy main contrib non-free

## DEBIAN SECURITY
deb http://security.debian.org/ wheezy/updates contrib non-free main
deb http://ftp.debian.org/debian wheezy-updates contrib non-free main
# deb-src http://security.debian.org/ wheezy/updates main

**Comment by jdupl** [comment]
@Kerwood this issue should be closed (user source mixup)

**Comment by shauder** [comment]
I changed my source to the above and only those and I got some package updates but I have the same dependency problems. I am going to try a fresh install. Thanks for all the help though.

**Comment by yelow79** [comment]
You can do
apt-get clean
apt-get update
apt-get dist-upgrade
apt-get -f install

The last one is just for good measure
Sent from my HTC One SV

----- Reply message -----

**Comment by shauder** [comment]
I ran 

apt-get update
apt-get upgrade
apt-get dist-upgrade

But I did not run 
apt-get -f install
or
apt-get clean

After I fixed the sources.

 I already did the reinstall as there was not much setup on that server yet so I figured a fresh start may be what I need.  On the new install I did discover the Debian squeezy repos are in there by default when I re-image with the template I am given (Debian 7.1 template so not sure what gives).  The other Ubuntu repo I had added myself was for just one package.

**Comment by yelow79** [comment]
Just for information sake...
Apt-get clean
Clears all of the old .deb packages and ensures that won't be re-installed.
Apt-get -f install
Tells apt to force install missing dependencies (sort of)

Sent from my HTC One SV

----- Reply message -----

**Comment by shauder** [comment]
Guys I think I know what happened. When I installed another package (not supported) I had to install libc6 from testing which upgraded several other packages and got my system all out of whack.  Anyways this is my theory.  Thanks for all the help, I am not normally using Debian so the help was very welcomed.

**Comment by yelow79** [comment]
I've screwed up a system that way before


Sent from my HTC One SV

----- Reply message -----
