### ISSUE TITLE
Request Nginx

### ISSUE THREAD

**Issue by cronner** [Kerwood/rtorrent.auto.install#43]
Optional Nginx instead of Apache2 would be great something like:

server {
	listen 440 ssl spdy;
		server_name DOMAIN.COM;
		ssl_certificate /etc/ssl/certs/nginx.pem;
		ssl_certificate_key /etc/ssl/private/nginx.key;

		client_max_body_size 20M; # Allow files up to 20M to be uploaded
		client_body_buffer_size 128k;
		client_body_timeout 7200;

	location / {
		root /www;
		index index.php index.html;
		auth_basic            "Restricted";
		auth_basic_user_file  .htpasswd;
	}

	location /RPC2 {
		include /etc/nginx/scgi_params;
		scgi_pass backend2;
	}

	location ~  \.php$ {
		# Filter out arbitrary code execution
		location ~ \..*/.*\.php$ {return 404;}
		include /etc/nginx/fastcgi_params;
		fastcgi_param SCRIPT_FILENAME /www$fastcgi_script_name;
		fastcgi_index index.php;
		fastcgi_pass  backend;
	}

	location ~ /\.ht {
		deny  all;
	}
}

	upstream backend {
		server unix:/var/run/php5-fpm.sock;
	}

	upstream backend2 {
		server unix:/tmp/rpc.socket;
	}

**Comment by Kerwood** [comment]
I haven't planned it, but you are welcome to fork the project.
