### ISSUE TITLE
Missing Tracker tab?

### ISSUE THREAD

**Issue by dvu0704** [Kerwood/rtorrent.auto.install#55]
I just installed the latest version "rtorrent.auto.install-2.1.1-Debian-Wheezy" and I have noticed, the "Tracker" tab is missing? Please advise how to fix this?

Cheers and Thanks!

**Comment by Kerwood** [comment]
Hmm.. Sounds like a rutorrent problem.. I really have no idea how to fix it.
Its the "Trackers" tab at the bottom between "Files" and "Peers" ?

**Comment by dvu0704** [comment]
No, if you highlight the torrent, scroll to the far right, you should see the tracker name for each torrent you downloaded.

**Comment by Kerwood** [comment]
Right click on one of the lables and you get a list of lables that you can disable or enable.

**Comment by dvu0704** [comment]
Nope, I am not seeing that option when right click on the label on the left side pane. This is the tab I am talking about http://i1.someimage.com/xBUEyU3.jpg

**Comment by dvu0704** [comment]
compared it with older version, there is no tracklabel in the plugins folder, but older version has it http://i1.someimage.com/qYXmX3Y.jpg

**Comment by Kerwood** [comment]
Well there you go :) .. Install the plugin.

**Comment by dvu0704** [comment]
Where can I find that plugin? if not, I can just copy it from my older server. Thanks!

**Comment by Kerwood** [comment]
3 second search on google.. First hit. https://code.google.com/p/rutorrent/wiki/PluginTracklabels

**Comment by dvu0704** [comment]
So, this plugin is missing from your new version, just want to report it and maybe you can fix it? Thanks for all the helps, I really appreciated it. Have a good day.

I am going to grab that plugin now :)

**Comment by Kerwood** [comment]
No.. Its not missing.. Plugins is only installed if you choose to. Tracklabels was never installed by default.

No problem :) .. You too.

**Comment by dvu0704** [comment]
So, do I need to re-install the entire rtorrent or just download the plugin from here and install it manually?

https://bintray.com/novik65/generic/ruTorrent

**Comment by Kerwood** [comment]
Just download the plugin and unpack it and put in /var/www/rutorrent/plugins folder. Or use the Plugins installer script https://raw.githubusercontent.com/Kerwood/rtorrent.auto.install/master/Plugins-installer-script-2.1

**Comment by dvu0704** [comment]
Thanks, I found the plugin install script and about to install it now :). Thanks again.

**Comment by Kerwood** [comment]
Np.

**Comment by dvu0704** [comment]
And BTW, I did not know that I can just re-run the plugin install script until now :), I am not a linux person, a lot of time, I need to google and find a way to spin-up my owned seedbox or fix some issues here and there.

FYI, I just install that trackLabel plugin, all looking good now. Thanks again and again :)

**Comment by Kerwood** [comment]
I am a Linux person. And I became that by googling my problems and issues. :)

No problem..
