### ISSUE TITLE
Debian issue

### ISSUE THREAD

**Issue by NVroom** [Kerwood/rtorrent.auto.install#57]
root@freeleech:~# chmod +x rtorrent.auto.install-2.1.1-Debian-Wheezy
root@freeleech:~# ./rtorrent.auto.install-2.1.1-Debian-Wheezy
./rtorrent.auto.install-2.1.1-Debian-Wheezy: line 4: syntax error near unexpected token `newline'
./rtorrent.auto.install-2.1.1-Debian-Wheezy: line 4: `<!DOCTYPE html>'

There is a problem?

**Comment by Kerwood** [comment]
Yes.. You havent downloaded the script.. 
The `<!DOCTYPE html>` indicates that you have downloaded a HTML site.

**Comment by NVroom** [comment]
I executed the commands that you listed, so the script was downloaded?

**Comment by Kerwood** [comment]
Which command is that ?

**Comment by dvu0704** [comment]
you properly need to get the latest script by issue the command line below.

wget https://raw.githubusercontent.com/Kerwood/rtorrent.auto.install/master/Rtorrent-Auto-Install-3.0.0-Debian-Wheezy

that's the latest script released 2 days ago?
