### ISSUE TITLE
Compile Libtorrent with..

### ISSUE THREAD

**Issue by ne0ark** [Kerwood/rtorrent.auto.install#58]
Compile libtorrent with --with-posix-fallocate. Then in the rtorrent.rc you can set system.file_allocate.set = yes or system.file_allocate.set = no depending use.

**Comment by Kerwood** [comment]
And what does that do ?

**Comment by ne0ark** [comment]
Pre-allocate all files to create and fully allocate every file you select to download immediately after starting the torrent job.

**Comment by Kerwood** [comment]
Sp you skip the "Checking.." part after the download is done ?

**Comment by ne0ark** [comment]
So all it does it pre-allocates the file.

**Comment by Kerwood** [comment]
Which means ?

**Comment by frantzz** [comment]
I guess it means that when you start the download of a torrent, rTorrent will pre-allocate the needed space on the disk.
