### ISSUE TITLE
Erreur script

### ISSUE THREAD

**Issue by tocks53** [Kerwood/rtorrent.auto.install#59]
Choose plugin to see info: 47

This plugin installs about 40 plugins. Download the plugin manually to see which plugins are included. 
https://bintray.com/novik65/generic/ruTorrent 
REMEBER TO REMOVE HTTPRPC AND RPC PLUGINS FOR LOGIN TO WORK!

Install 'Plugins v3.6'. [y/n]: y
--2015-04-03 12:45:52--  http://dl.bintray.com/novik65/generic/plugins-3.6.tar.gz
Résolution de dl.bintray.com (dl.bintray.com)... 5.153.24.114
Connexion vers dl.bintray.com (dl.bintray.com)|5.153.24.114|:80... connecté.
requête HTTP transmise, en attente de la réponse... 302 
Emplacement : http://d29vzk4ow07wi7.cloudfront.net/617625cda45c689f5505fbfdfb6cc4000bc6b1d9?response-content-disposition=attachment%3Bfilename%3D%22plugins-3.6.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvNjE3NjI1Y2RhNDVjNjg5ZjU1MDVmYmZkZmI2Y2M0MDAwYmM2YjFkOT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMnBsdWdpbnMtMy42LnRhci5neiUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTQyODA1ODAxMn0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=h3hzmOulQ-HDOQA0PmS9TI9NfoU0e3d28LEiNprXWyO-ECjY2TB1b~mb852ltoiFWiEUsOduCr9uJtu2BmlKEBgnw1pntsN0cpDLj-~FMB0wJHI-hrLnzYS-DFnnspWmR3OK-EIyWdMVVcNIzXK7kFZ7B1FiCTVqsNcIsbhDdlnehYHwFTOEVIRlG3BsKmyBeJ1GK3J8Moarz8wpwlmw8E6c-SxseGIGEiSkQPzoaz5Nnr3BVyCfiVX83G6uUXtRYdzmypdGQ746juqqpyXfAdWcFH6t2TYJBpgUAe0jjKW81PtmQjj0yb2WDDdrMI2Un03J41RiszLRp6~fFJCzPg__&Key-Pair-Id=APKAIQIOJCQ5764M5VTQ [suivant]
--2015-04-03 12:45:52--  http://d29vzk4ow07wi7.cloudfront.net/617625cda45c689f5505fbfdfb6cc4000bc6b1d9?response-content-disposition=attachment%3Bfilename%3D%22plugins-3.6.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvNjE3NjI1Y2RhNDVjNjg5ZjU1MDVmYmZkZmI2Y2M0MDAwYmM2YjFkOT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMnBsdWdpbnMtMy42LnRhci5neiUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTQyODA1ODAxMn0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=h3hzmOulQ-HDOQA0PmS9TI9NfoU0e3d28LEiNprXWyO-ECjY2TB1b~mb852ltoiFWiEUsOduCr9uJtu2BmlKEBgnw1pntsN0cpDLj-~FMB0wJHI-hrLnzYS-DFnnspWmR3OK-EIyWdMVVcNIzXK7kFZ7B1FiCTVqsNcIsbhDdlnehYHwFTOEVIRlG3BsKmyBeJ1GK3J8Moarz8wpwlmw8E6c-SxseGIGEiSkQPzoaz5Nnr3BVyCfiVX83G6uUXtRYdzmypdGQ746juqqpyXfAdWcFH6t2TYJBpgUAe0jjKW81PtmQjj0yb2WDDdrMI2Un03J41RiszLRp6~fFJCzPg__&Key-Pair-Id=APKAIQIOJCQ5764M5VTQ
Résolution de d29vzk4ow07wi7.cloudfront.net (d29vzk4ow07wi7.cloudfront.net)... 54.192.79.66, 54.230.79.113, 54.230.79.3, ...
Connexion vers d29vzk4ow07wi7.cloudfront.net (d29vzk4ow07wi7.cloudfront.net)|54.192.79.66|:80... connecté.
requête HTTP transmise, en attente de la réponse... 200 OK
Taille : 742728 (725K) [application/unknown]
Enregistre : «plugins-3.6.tar.gz.2»

100%[===================================================================================================================================================================>] 742 728      554K/s   ds 1,3s    

2015-04-03 12:45:54 (554 KB/s) - «plugins-3.6.tar.gz.2» enregistré [742728/742728]

tar: /var/www/html/rutorrent : open impossible: Aucun fichier ou dossier de ce type
tar: Error is not recoverable: exiting now

Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
libmediainfo0 est déjà la plus récente version disponible.
libzen0 est déjà la plus récente version disponible.
mediainfo est déjà la plus récente version disponible.
php5-geoip est déjà la plus récente version disponible.
curl est déjà la plus récente version disponible.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 2 non mis à jour.
Cannot access PPA (https://launchpad.net/api/1.0/~jon-severinsson/+archive/ffmpeg) to get PPA information, please check your internet connection.

**Comment by Kerwood** [comment]
Fixed it ... Use the version 3.0.1
