### ISSUE TITLE
srcipt wont work

### ISSUE THREAD

**Issue by kolankobulka** [Kerwood/rtorrent.auto.install#60]
http adress in script to libtorrent and rtorrent, are wrong. 
http://libtorrent.rakshasa.no are down/dead.
When installing, script stopped at downloading libtorrent, and retrying in endlessly...

**Comment by Kerwood** [comment]
Yeah.. I know.. 
Rakshasa.no is down at the moment.

**Comment by Kerwood** [comment]
Made an 3.0.2 version with working site..

https://raw.githubusercontent.com/Kerwood/rtorrent.auto.install/master/Rtorrent-Auto-Install-3.0.2-Debian-Wheezy

**Comment by kolankobulka** [comment]
THX, links works,  but now, on RPi2 have this error: Could not compile XMLRPC-C test.
I have latest raspbian on pi... trying various methods and always have this error.

**Comment by Kerwood** [comment]
Cant help you with that, sorry.. Script is made for Wheezy
