### ISSUE TITLE
Fail in connecting to libtorrent.rakshasa.no

### ISSUE THREAD

**Issue by robot2xl** [Kerwood/rtorrent.auto.install#61]
Connecting to libtorrent.rakshasa.no (libtorrent.rakshasa.no)|66.220.1.220|:80... failed: Connection timed out.

**Comment by Kerwood** [comment]
Use the newest version.. 
[Rtorrent-Auto-Install-3.0.2-Debian-Wheezy](https://raw.githubusercontent.com/Kerwood/rtorrent.auto.install/master/Rtorrent-Auto-Install-3.0.2-Debian-Wheezy)
