### ISSUE TITLE
no connection

### ISSUE THREAD

**Issue by YaPaY** [Kerwood/rtorrent.auto.install#63]
First, thank you for amazing script. I installed this to my Pi. 
When I open rutorrent I see this message "No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file."

Console: 
apt-cache policy rtorrent
rtorrent:
  Installed: (none)
  Candidate: 0.9.2-1
  Version table:
     0.9.2-1 0
        500 http://mirrordirector.raspbian.org/raspbian/ wheezy/main armhf Packages

also

cannot find rtorrent binary in PATH /usr/bin:/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin

Thanks

**Comment by Kerwood** [comment]
I haven't installed it on a Pi so i cant really help you. The script is designed to Wheezy.

**Comment by jdupl** [comment]
@YaPaY rtorrent is normally compiled by the script and does not use the package from the repositories. 
Perhaps you might want to retry with the package uninstalled. 
`apt-get purge rtorrent`

**Comment by YaPaY** [comment]
ok @jdupl I will try it. Thanks

**Comment by Kerwood** [comment]
Haven't heard from you, so im closing :)
