### ISSUE TITLE
Choice of the webserver for the raspberry

### ISSUE THREAD

**Issue by miracle091** [Kerwood/rtorrent.auto.install#77]
The raspberry works with the 3 most used web server, Apache2, NGinX and Lighttpd.
Cause i want to make the script for raspberry, even better, what is the best choise?

**Comment by jdupl** [comment]
I prefer nginx over lighttpd.

Apache eats too much ram or takes too much cpu ?

**Comment by miracle091** [comment]
I prefer nginx too.

Apache takes both, but depends on configuration. Anyway for rutorrent is a overkill, just cause required to much cpu cycles for work wells with 10+ torrent actives.

**Comment by Kerwood** [comment]
A lot of people use nginx and I have heard a lot good about it but dont know it supports CGI. But why shouldnt it ?..

**Comment by miracle091** [comment]
In the next days, the script with nginx on default, is ready to try & test.
For now work on every debian-like distro, need to test more CFLAGS to make it a little more fast.

**Comment by Kerwood** [comment]
Please make a separate script for installing rutorrent with nginx. I still want an option for Apache.
