### ISSUE TITLE
Init.d script don't work on Raspbian

### ISSUE THREAD

**Issue by miracle091** [Kerwood/rtorrent.auto.install#78]
The init.d script, after 3 days from installation, don't work anymore. I am trying to understand what is wrong with that.
For now use the manual command to start/stop rtorrent.

Sorry for the inconvenience.

**Comment by Kerwood** [comment]
Does Raspbian use init.d or systemd ?

**Comment by miracle091** [comment]
For now is a pure wheezy port, use init.d
