### ISSUE TITLE
Issue with download link.

### ISSUE THREAD

**Issue by GKNSB** [Kerwood/rtorrent.auto.install#85]
Hey there. 
It's nothing important  I just noticed that "raw.github.com" in your Readme file like:

wget https://raw.github.com/Kerwood/rtorrent.auto.install/master/rtorrent.auto.install-X.X.X-Debian-Wheezy

should be changed to 
"raw.githubusercontent.com"

cheers and many thanks for the great script :D

**Comment by Kerwood** [comment]
Thanks.. Your welcome.
