### ISSUE TITLE
Debian Jessie, 404 error in GUI

### ISSUE THREAD

**Issue by bartolije** [Kerwood/rtorrent.auto.install#94]
After script run, got a "Bad response from server: (404 " in my rtorrent log

**Comment by miracle091** [comment]
Can you post the entire error from your log?

**Comment by bartolije** [comment]
Here what I got on my GUI.
http://i.imgur.com/cwyEM2U.png

Nginx logs are empty.
http://i.imgur.com/C4qj6uA.png

Tell me if you need more details.
I'm on Debian 8 (Jessie)
(And i'm a newbie :/ )

**Comment by miracle091** [comment]
Seem than rtorrent is not started, is a know issue for debian jessie.
You need to start it from console... anyway this is the command for start it:
<code>tmux new-session -s rt -n rtorrent -d rtorrent</code>

**Comment by bartolije** [comment]
Hello,

I have installed tmux, and run the command.
Exacuted, but still have the message.
No logs available.

In my service list, I got:
<myUsername>-rtorrent and rtorrent-init
Is it normal that both are here?

Maybe something wrong on my side?

**Comment by miracle091** [comment]
Kill both and rerun the command above.

**Comment by bartolije** [comment]
Well, here my last issue after doing what you told me.
After that, if it isn't working properly, i'm gonna back-up my files, and wipe my server, since I feel like the issue is on my side.

Anyways, thanx a lots for taking time to help me.

----
Link with rTorrent invalid. That check is running . 
heck the configuration of $ scgi_port and $ scgi_host In config.php and scgi_port In the configuration file of rTorrent .
