### ISSUE TITLE
Missing file/directory

### ISSUE THREAD

**Issue by Quintenps** [Kerwood/rtorrent.auto.install#97]
When running the script I noticed that it was missing files/directory, resulting in an unsuccessful installation.

"Rtorrent-Auto-Install-3.0.2-Raspbian-Wheezy: line 674: cd: xmlrpc-c: No such file or directory
Rtorrent-Auto-Install-3.0.2-Raspbian-Wheezy: line 675: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
rm: cannot remove `xmlrpc-c': No such file or directory"

And

"Rtorrent-Auto-Install-3.0.2-Raspbian-Wheezy: line 698: cd: rtorrent-0.9.4: No such file or directory
Rtorrent-Auto-Install-3.0.2-Raspbian-Wheezy: line 699: ./autogen.sh: No such file or directory
Rtorrent-Auto-Install-3.0.2-Raspbian-Wheezy: line 700: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
removed `rtorrent/libtorrent-0.13.4.tar.gz'
removed `rtorrent/0.13.4.tar.gz'
removed directory: `rtorrent'"

Etc.

Thanks :)

**Comment by Quintenps** [comment]
Hm, Might have been a problem on my end. Ran it again with a fresh install and it seemed to have worked now.

**Comment by jdupl** [comment]
@Kerwood issue can be closed
